version: '3.9'

services:
  keycloak-postgres:
    image: 'library/postgres:${KC_POSTGRES_IMAGE_TAG:-latest}'
    container_name: '${POSTGRES_CONTAINER_NAME:-postgres}'
    restart: on-failure
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -d postgres
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - '${KC_POSTGRES_PORT_MAPPING:-5435}:5432'
    deploy:
      resources:
        limits:
          memory: 16G

  keycloak:
    image: 'quay.io/keycloak/keycloak:20.0.2'
    container_name: keycloak
    command:
      - start --db postgres --proxy edge --import-realm --hostname-strict-https false --hostname-strict false
    environment:
      KC_DB_URL: 'jdbc:postgresql://keycloak-postgres:5432/postgres'
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8282:8080'
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master" ]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s

  db:
    image: postgres:15-alpine
    container_name: postgres_15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=hrm
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: